FROM oven/bun:1.3.14 AS build
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY tsconfig*.json vite.config.ts index.html components.json ./
COPY public ./public
COPY src ./src
COPY server ./server

# Skip the `tsc -b` step from package.json's `build` script: routeTree.gen.ts
# is generated by the tanstack-router Vite plugin at the start of `vite build`,
# so typecheck must run *after* bundling — and we run typecheck in CI anyway.
RUN bunx vite build

FROM oven/bun:1.3.14-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3001
ENV CLOUDSHELF_DB=/app/data/cloudshelf.db

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production

COPY --from=build /app/dist ./dist
COPY server ./server
COPY tsconfig.server.json tsconfig.json ./

RUN mkdir -p /app/data
VOLUME ["/app/data"]

EXPOSE 3001
CMD ["bun", "server/index.ts"]
